name: Update data

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache perl scripts & libs
        uses: actions/cache@v2
        with:
          path: |
            ./bin
            ./local
          key: perl
      - name: Save date for cache
        run: |
          date +'%Y-%m-%d' > cache-date
          cat cache-date
      - name: Cache data files
        uses: actions/cache@v2
        with:
          path: |
            ./data
          key: data-${{ hashFiles('cache-date') }}
          restore-keys: |
            data-${{ hashFiles('cache-date') }}
            data-
      - name: Install cpm
        run: |
          set -e
          set -x
          if [ ! -x ./bin/cpm ]; then
              mkdir ./bin && \
              curl -fsSL https://git.io/cpm > ./bin/cpm && \
              chmod 0755 ./bin/cpm
          fi
      - name: Install prereqs
        run: |
          set -e
          set -x
          ./bin/cpm install
      - name: Generate data
        run: PERL5LIB=$PERL5LIB:$(pwd)/local/lib/perl5 ./report.pl
      - name: Publish data
        uses: actions/upload-artifact@v2
        with:
          name: summary.json
          path: ./summary.json
      - name: Trigger Render deploy
        env:
          RENDER_WEBHOOK_URL: ${{ secrets.RENDER_WEBHOOK_URL }}
        run: wget "$RENDER_WEBHOOK_URL"
